spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:server-1}

---

spring:
  config:
    activate:
      on-profile: server-1
  application:
    name: server-1

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: server-2
  application:
    name: server-2
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: server-3
  application:
    name: server-3
server:
  port: 8082