spring:
  profiles:
    active: server-1

---

spring:
  profiles:
    default: server-1
server:
  port: 8080

---

spring:
  profiles:
    default: server-2
server:
  port: 8081

---

spring:
  profiles:
    default: server-3
server:
  port: 8082